### ISSUE TITLE
Test failure. Got: GMT-4

### ISSUE THREAD

**Issue by szabgab** [zoffixznet/perl6-WWW-Google-Time#3]
```
# zef install WWW::Google::Time
===> Searching for: WWW::Google::Time
===> Searching for missing dependencies: HTTP::Tinyish
===> Testing: HTTP::Tinyish
t/01-basic.t .. ok
All tests successful.
Files=1, Tests=1,  0 wallclock secs
Result: PASS
===> Testing [OK] for HTTP::Tinyish
===> Testing: WWW::Google::Time:ver('1.002002')

# Failed test 'timezone looks right'
# at t/01-time.t line 23
t/01-time.t ..1/?#      expected: '/^ [EST | EDT] $/'
#      got: 'GMT-4'
# Looks like you failed 1 test of 12
t/01-time.t .. Failed 1/12 subtests

Test Summary Report
-------------------
t/01-time.t (Wstat: 0 Tests: 12 Failed: 1)
  Failed tests:  6
Files=1, Tests=12,  2 wallclock secs
Result: FAILED
===> Testing [FAIL]: WWW::Google::Time:ver('1.002002')
Aborting due to test failure: WWW::Google::Time:ver('1.002002') (use --force to override)
  in code  at /usr/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 306
  in method test at /usr/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 285
  in code  at /usr/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 457
  in sub  at /usr/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 454
  in method install at /usr/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 560
  in sub MAIN at /usr/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 123
  in block <unit> at /usr/share/perl6/site/resources/3DD33EF601FD300095284AE7C24B770BAADAF32E line 1
```

**Comment by zoffixznet** [comment]
Should be fixed now. Thanks.

**Comment by szabgab** [comment]
Thanks but I still get the same error and it still reports ```Testing: WWW::Google::Time:ver('1.002002')```
Do I need to tell something to ```zef``` to fetch the newer version from GitHub?

**Comment by zoffixznet** [comment]
You may need to run `zef update` and you may have to wait 15-60 minutes before the ecosystem list gets updated. Or you can clone and test from dir instead:

```bash
cd $(mktemp -d);
git clone https://github.com/zoffixznet/perl6-WWW-Google-Time .
zef test .
````

You can also run `zef install .` if you were planning to install the module.

**Comment by szabgab** [comment]
Finally I had time to try it again. It worked now. Thanks!
